// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutOptimization.Repository;

#nullable disable

namespace WorkoutOptimization.Repository.Migrations
{
    [DbContext(typeof(WorkoutOptimizationDbContext))]
    partial class WorkoutOptimizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutOptimization.Models.GyroscopeData", b =>
                {
                    b.Property<int>("GyroscopeDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GyroscopeDataId"));

                    b.Property<int>("AccelX")
                        .HasColumnType("int");

                    b.Property<int>("AccelY")
                        .HasColumnType("int");

                    b.Property<int>("AccelZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GyrosX")
                        .HasColumnType("int");

                    b.Property<int>("GyrosY")
                        .HasColumnType("int");

                    b.Property<int>("GyrosZ")
                        .HasColumnType("int");

                    b.HasKey("GyroscopeDataId");

                    b.ToTable("GyrosScropeData");

                    b.HasData(
                        new
                        {
                            GyroscopeDataId = 1,
                            AccelX = 1,
                            AccelY = 1,
                            AccelZ = 1,
                            Date = new DateTime(2025, 3, 17, 16, 56, 58, 305, DateTimeKind.Local).AddTicks(1723),
                            GyrosX = 1,
                            GyrosY = 1,
                            GyrosZ = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
