server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Ez a lényeg: ha nem találja a fájlt, adja vissza az index.html-t (Angular Routing miatt)
        try_files $uri $uri/ /index.html;
    }
}