<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Interfaces\IShoulderPressLogic.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.13" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
	  <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkoutOptimization.Models\WorkoutOptimization.Models.csproj" />
    <ProjectReference Include="..\WorkoutOptimization.Repository\WorkoutOptimization.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Onxx\best_model.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Onxx\hr_model_tf2onnx.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
